# Generated by Django 4.2.3 on 2023-08-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cartas', '0002_alter_card_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='nombre_carta',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
