# Generated by Django 4.2.3 on 2023-08-29 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cartas', '0003_card_nombre_carta'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
