# Generated by Django 4.2.3 on 2023-09-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cartas', '0004_card_is_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cardgames',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('games', models.IntegerField()),
                ('sub', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
