# Generated by Django 4.2.3 on 2023-09-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cartas', '0005_cardgames'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardgames',
            name='img',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
